# Camera
CAMERA_INDEX = 0
FRAME_WIDTH = 1280
FRAME_HEIGHT = 720
FPS = 30
CAMERA_BACKEND = "DSHOW"
MIRROR_CAMERA = True

# MediaPipe
MAX_NUM_HANDS = 1
MODEL_COMPLEXITY = 1
MIN_DETECTION_CONFIDENCE = 0.7 # 0.5
MIN_TRACKING_CONFIDENCE = 0.8 # 0.9

# Serial
SERIAL_PORT = "COM9"
BAUDRATE = 115200
SERIAL_WAIT_SECONDS = 2

# Mouse movement
SENSITIVITY_X = 2.5
SENSITIVITY_Y = 2.5
DEADZONE = 3
MAX_MOVE = 60

# Smoothing
ENABLE_SMOOTHING = True
SMOOTHING_ALPHA = 0.45 # 0.35

# Gesture
PINCH_PRESS_THRESHOLD = 25 # 25
PINCH_RELEASE_THRESHOLD = 50 # 65
CLICK_HOLD_TIME = 0.18

# Display
WINDOW_NAME = "Webcam Mouse"
SHOW_PREVIEW = True
SHOW_FPS = True
BLACK_BACKGROUND_PREVIEW = True