# Camera
CAMERA_INDEX = 0
FRAME_WIDTH = 1280
FRAME_HEIGHT = 720
FPS = 30
CAMERA_BACKEND = "DSHOW"

MIRROR_CAMERA = True

# MediaPipe
MAX_NUM_HANDS = 1
MODEL_COMPLEXITY = 1
MIN_DETECTION_CONFIDENCE = 0.7
MIN_TRACKING_CONFIDENCE = 0.7

# Serial
SERIAL_PORT = "COM9"
BAUDRATE = 115200
SERIAL_WAIT_SECONDS = 2

# Mouse movement
SENSITIVITY_X = 1.3
SENSITIVITY_Y = 1.3
DEADZONE = 1
MAX_MOVE = 60

# Gesture
PINCH_THRESHOLD = 45

# Display
WINDOW_NAME = "Webcam Mouse"
SHOW_PREVIEW = True
SHOW_FPS = True